GenericBlog/GenericBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about),
    path('', article_views.article_list, name="home"),

]
# N.B I know this is bad practice, better to use AWS to host images
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GenericBlog/accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout', views.logout_view, name='logout'),
]

GenericBlog/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [

    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>', views.article_detail, name="detail"),
]

GenericBlog/accounts/models.py
from django.db import models

# Create your models here.

GenericBlog/articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(null=True)
    thumbnail = models.ImageField(default='default.jpg', blank=True)
    date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

GenericBlog/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','slug','thumbnail','body']

GenericBlog/GenericBlog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
  # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
   # return HttpResponse('about')
    return render(request, 'about.html')

GenericBlog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list'
                            )
    else:
        form = UserCreationForm()

    return render(request, 'accounts/register.html', {'form': form})


def login_view(request):
    if request.method =='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('articles:list')

GenericBlog/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


def article_list(request):
    articles = Article.objects.all().order_by('date')

    return render(request, 'articles/article_list.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

GenericBlog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="contentcontainer">
        <h1 class="articles">Login</h1>
        <div class="article-content">
            <form class="site-form" action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                {{form}}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{request.GET.next}}">
                {% endif %}
                <input type="submit" value="Login">
            </form>
        </div>
    </div>
{% endblock %}

GenericBlog/accounts/templates/accounts/register.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="contentcontainer">
        <h1 class="articles">Register</h1>
        <div class="article-content">
            <form class="site-form" action="./register" method="post">
                {% csrf_token %}
                {{form}}

                <input type="submit" value="Register">
            </form>
        </div>
    </div>
{% endblock %}

GenericBlog/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% block content %}
 <div class="create-article">

     <div class="contentcontainer">
         <div class="articles">
             <h2>Create a new article</h2>
             <br>
             <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 {{form}}
                 <input type="submit" value="Create">
             </form>
         </div>

     </div>
 </div>
 <script src="/static/sluggy.js"></script>
{% endblock %}

GenericBlog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% block content %}

<div class="contentcontainer">
    <div class="article-content">
        <h2>{{article.title}}</h2>
        <p>{{article.date}}</p>
        <img src="{{ article.thumbnail.url }}" class="fit"/>
        <p class="article-text">{{article.body}}</p>
    </div>

</div>




{% endblock %}

GenericBlog/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="contentcontainer">
    <p class="articles">Here is a list of articles</p><br>
    <div class="articles">
        {% for article in articles %}
        <div class="article">
            <h1><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}} </a></h1>
            <p>{{article.date}}</p>
            <br><br><p>{{article.snippet}}</p> <br><br>
            <p class ="author">added by: {{article.author.username}}</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

GenericBlog/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
   <h1>About</h1>
<p>Welcome, this Django page is in development.</p>
</body>
</html>

GenericBlog/templates/base_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">

        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <title>Article List</title>

    </head>

    <body>

        <header class="navwrapper">

            <a href="{% url 'home' %}"><img src="{% static 'IH.png' %}" height="100px" width="100px"/></a>
                <nav>
                    <ul>
                        {% if user.is_authenticated %}
                        <li>
                            <form class="logout-line" action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit"> Logout </button>
                            </form>
                        </li>
                        <li><a href="{% url 'articles:create'%}" class="highlight">New Article</a> </li>

                        {% else %}
                        <li><a href="{% url 'accounts:login'%}" class="highlight">Login</a> </li>
                        <li><a href="{% url 'accounts:register'%}"class="highlight">Register</a> </li>

                        {% endif %}
                    </ul>
                </nav>
        </header>

        <div class="wrapper">
            {% block content %}

            {% endblock %}
        </div>

    </body>
</html>

GenericBlog/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage</h1>
<p>Welcome, this Django page is in development.</p>
</body>
</html>